version: '3.5'

services:
  web:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: ${DOCKER_NAME}_app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - dashboard_nfsmount:/var/www/html
      - ./docker/apache2/sites-available:/etc/apache2/sites-available:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
    ports:
      - 8095:80
    networks:
      - exads
  mysql-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - '3311:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=
    container_name: ${DOCKER_NAME}_db
    networks:
      - exads
volumes:
  dashboard_nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/service"

networks:
  exads: